#!/usr/bin/env python
# -*- coding: utf-8 -*-
import numpy as np
import cv2
from cv2 import aruco

# 画像の読み込み
#capture = cv2.VideoCapture('ArUco/ArUco-test-input/IMG_0934.JPEG')
capture = cv2.VideoCapture(0)

while capture.isOpened():
    ret, imag = capture.read()
 # マーカの検出
    aruco_dict = aruco.getPredefinedDictionary(aruco.DICT_4X4_250)
    parameters = aruco.DetectorParameters()
    detector = aruco.ArucoDetector(aruco_dict, parameters)
    corners, ids, rejectedImgPoints = detector.detectMarkers(imag)
        # マーカが検出された場合
    if ids:
        print('corners:', corners, '\nids:', ids, '\nrejectedImgPoints:', rejectedImgPoints)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            aruco.drawDetectedMarkers(imag, corners, ids)
            cv2.imshow('Detected ArUco markers', imag)
            cv2.waitKey(0)
            cv2.destroyAllWindows()
            break
    else:
        print('No markers found')
        cv2.imshow('Connot Detected ArUco marker', imag)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
capture.release()
cv2.destroyAllWindows()
